inherit_from:
- .rubocop_airbnb.yml

Rails:
 Enabled: true

LineLength:
 max: 130

AllCops:
 Exclude:
  - 'db/**/*'
  - 'bin/*'
  - 'config/environments/*'
  - 'config/application.rb'
  - 'config/initializers/*'
  - 'config/spring.rb'
  - 'lib/tasks/*'
  - 'vendor/**/*'
  - 'app/helpers/notifications_helper.rb'
  - 'spec/**/*'
